spring:
  application:
    name: price-aggregator-api
  profiles:
    include: marketplaceConfig
  cloud:
    config:
      uri: http://localhost:8888
      username: config-service-client
      password: ${CONFIG_SERVICE_SECRET}
      fail-fast: true
  config:
    import: configserver:${spring.cloud.config.uri}
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    openai:
      api-key: ENC(M+h/SHskI3b8WOYsdllhXYzBUZigYYFmXo6gf9z1bQ6Z3AVAzuFGw62uUVrKMhd9zGTb312FWLIA7Ieo8A2xHZH73lzdyJeFCppdw3X+Vr42t47uYDnGWm42hUPklR9+)
resilience4j:
  ratelimiter:
    instances:
      openai:
        limit-for-period: 3
        limit-refresh-period: 1m
        timeout-duration: 1m
        register-health-indicator: true
price-aggregator-api:
  config:
    subcategories:
      max-count: 3
  selenide:
    timeout: 4000
    screenshots-enabled: false
    page-source-enabled: false
  web-driver:
    headless: true
    pool:
      capacity: 10
      timeout-millis: 60000
  api.key: ENC(isEh0rI7DYDevr398EXAL58p5a8OYRcohdnTvCMNlZ9CKxc59MmSyeV5bwfI9tSsAAeVmQYioh4Ek3ZiFR1y/w==)
management:
  endpoints:
    web:
      exposure:
        include: refresh
