spring:
  application:
    name: price-aggregator-api
  profiles:
    include: marketplaceConfig
  cloud:
    config:
      uri: http://localhost:8888
      username: config-service-client
      password: ${CONFIG_SERVICE_SECRET}
      fail-fast: true
  config:
    import: configserver:${spring.cloud.config.uri}
price-aggregator-api:
  selenide:
    headless: true
    timeout: 4000
    http:
      proxy: 65.109.199.184:80
  api.key: ENC(isEh0rI7DYDevr398EXAL58p5a8OYRcohdnTvCMNlZ9CKxc59MmSyeV5bwfI9tSsAAeVmQYioh4Ek3ZiFR1y/w==)
management:
  endpoints:
    web:
      exposure:
        include: refresh
