spring:
  application:
    name: price-aggregator-api
  profiles:
    include: marketplaceConfig
price-aggregator-api:
  selenide.headless: true
  api.key: ENC(isEh0rI7DYDevr398EXAL58p5a8OYRcohdnTvCMNlZ9CKxc59MmSyeV5bwfI9tSsAAeVmQYioh4Ek3ZiFR1y/w==)
